### ISSUE TITLE
Support .net Core

### ISSUE THREAD

**Issue by willtoto** [tmsmith/Dapper-Extensions#204] opened 2018-10-20 07:47 UTC
Support .net Core

**Comment by robsonj** [comment] 2018-11-21 17:48
I wondered if there were any plans to support .Net Core etc please?

**Comment by robsonj** [comment] 2018-11-21 17:48
I'd be happy to contribute if the project is not dead.

**Comment by robsonj** [comment] 2018-12-06 03:01
Pull request #209

**Comment by robsonj** [comment] 2018-12-06 03:02
Think I have the old dnxcore project working with NetStandard & NetFramework. Need to port the test projects over to utilize it I think, then remove the old code

**Comment by robsonj** [comment] 2018-12-07 04:08
Cleaned everything up and ported the nupkg to the new csproj format way of packaging also

**Comment by k3davis** [comment] 2018-12-14 13:35
Thanks @robsonj for your efforts. I hope @tmsmith is able to review and merge these changes to add netstandard support. If the repo is really abandoned, perhaps you can maintain a fork?

**Comment by robsonj** [comment] 2018-12-14 13:49
Looks like it is dead. The issue is getting a new nuget package published. I sent the owners an email via nuget.org, hopefully we'll get some sort of response. If they'd be happy to add me as an owner, I could get a new nuget package published.

**Comment by wolszakp** [comment] 2019-04-15 11:46
Any news with porting to .net core?

**Comment by istrupin** [comment] 2019-11-01 22:27
> Looks like it is dead. The issue is getting a new nuget package published. I sent the owners an email via nuget.org, hopefully we'll get some sort of response. If they'd be happy to add me as an owner, I could get a new nuget package published.

Checking back a year later -- any news?  Or have you made your own fork?

**Comment by robsonj** [comment] 2019-11-01 22:41
We merged in the code to our own code base months ago. Gave up trying to help

**Comment by gismofx** [comment] 2019-11-02 00:23
How about sharing your fork?

**Comment by chrisjmccrum** [comment] 2019-11-02 16:33
Thank you for your efforts @robsonj! I was just about to start refactoring this project until I came across this thread. Do you mind contributing your work in a public fork? It would be greatly appreciated and save this developer a good chunk of duplicate work!

Thanks again!

**Comment by valfrid-ly** [comment] 2021-03-20 13:28
It's is compatible with net core but soon I'll be a version that would integrate all versions

**Comment by valfrid-ly** [comment] 2022-02-22 21:56
Version 1.7.0 onwards is Core compatible

**Closed by valfrid-ly** 2022-02-22 21:56 UTC

**Comment by grofit** [comment] 2022-02-23 12:29
Whenever I try and import this into a .net standard 2.0 project it blows up saying that it cannot resolve `Slapper.AutoMapper`.

Looking at that lib it seems to have an issue around there is a version that is .net standard 2.1 and a version which is .net standard 2.0, but I guess while your repo supports .net standard 2.0 that dependency doesnt?
