### ISSUE TITLE
insert error

### ISSUE THREAD

**Issue by eyupyuksel** [tmsmith/Dapper-Extensions#284] opened 2021-12-16 18:54 UTC
Hello, 
I am getting an error after insert.
Object of type 'System.Int64' cannot be converted to type 'System.Int32'.

**Comment by ALMMa** [comment] 2021-12-19 14:19
Duplicate of: https://github.com/tmsmith/Dapper-Extensions/issues/278

**Closed** 2022-02-19 21:56 UTC
Labels: duplicate
